{% set version = "3.9.0" %}
{% set name = "sleef" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/shibatch/{{ name }}/archive/{{ version }}.tar.gz
  sha256: af60856abac08a3b5e72a8d156dd71fec1f7ac23de8ee67793f45f9edcdf0908

build:
  number: 1
  string: {{ openmp_impl | replace("-", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('sleef', max_pin='x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
    - ninja-base  # [unix]
  host:
    - libgomp {{ cxx_compiler_version }}      # [openmp_impl == "libgomp"]
    - intel-openmp                            # [openmp_impl == "intel-openmp"]
    - llvm-openmp {{ cxx_compiler_version }}  # [openmp_impl == "llvm-openmp"]
  run:
    - libgomp       # [openmp_impl == "libgomp"]
    - intel-openmp  # [openmp_impl == "intel-openmp"]
    - llvm-openmp   # [openmp_impl == "llvm-openmp"]

test:
  commands:
    - test -f $PREFIX/include/sleef.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\sleef.h exit 1  # [win]

about:
  home: https://sleef.org
  license: BSL-1.0
  license_file: LICENSE.txt
  license_family: BSD
  summary: SIMD library for evaluating elementary functions
  description: |
    SLEEF stands for SIMD Library for Evaluating Elementary Functions.
    It implements manually vectorized versions of all C99 real floating
    point math functions. It can utilize SIMD instructions that are available
    on modern processors.
  dev_url: https://github.com/shibatch/sleef
  doc_url: https://sleef.org

extra:
  recipe-maintainers:
    - bluescarni
