{% set version = "3.5.1" %}

package:
  name: sleef
  version: {{ version }}

source:
  url: https://github.com/shibatch/sleef/archive/{{ version }}.tar.gz
  sha256: 415ee9b1bcc5816989d3d4d92afd0cd3f9ee89cbd5a33eb008e69751e40438ab
  patches:
    - patches/install_dll.diff  # [win]
    - patches/353.patch
    - patches/355.patch
    - patches/358.patch
    - patches/359.patch

build:
  number: 1
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('sleef', max_pin='x') }}
  skip: true  # [win and vc<14]
  ignore_run_exports_from:
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja        # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - openssl {{ openssl }}
  run:
    - openssl 3.*

test:
  commands:
    - test -f $PREFIX/include/sleef.h                          # [unix]
    - if not exist %PREFIX%\\Library\\include\\sleef.h exit 1  # [win]

about:
  home: https://sleef.org/
  license: BSL-1.0
  license_file: LICENSE.txt
  license_family: BSL-1.0
  summary: SIMD library for evaluating elementary functions
  description: |
    SLEEF stands for SIMD Library for Evaluating Elementary Functions.
    It implements manually vectorized versions of all C99 real floating
    point math functions. It can utilize SIMD instructions that are available
    on modern processors.
  dev_url: https://github.com/shibatch/sleef
  doc_url: https://sleef.org/

extra:
  recipe-maintainers:
    - bluescarni
